# Generated by Django 4.2.3 on 2023-07-15 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
